default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: shopping_cart_development

test:
  <<: *default
  database: shopping_cart_test

production:
  <<: *default
  database: shopping_cart_production
  username: shopping_cart
  password: <%= ENV['SHOPPING_CART_DATABASE_PASSWORD'] %>
